#!/usr/bin/env bash
# Script to install Nginx, set default page content, and start the service

# Update system package repositories
apt-get update -y

# Install Nginx non-interactively
apt-get install -y nginx

# Overwrite the default index.html with the required string
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Start / Restart Nginx using service instead of systemctl
service nginx restart
